baseURL = 'https://rezzamula.com/'
languageCode = 'en-us'
title = 'RezzaMula'
disableHugoGeneratorInject = true
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  author = "authors"