baseURL = 'https://rezzamula.com/'
languageCode = 'en-us'
title = 'RezzaMula'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  author = "authors"
  category = 'categories'
  tag = 'tags'
  story = 'stories'